os: osx

language: ruby

ruby:
    - 2.5
    - 2.6
    - 2.7

install: 
    - bundle install
    - brew install --build-from-source formula/fibonacci_sequence.rb

script:
    - rubocop
    - brew test formula/fibonacci_sequence.rb
