# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class 1Pass < Formula
  desc "1password cli wrapper for easy credential retrieval"
  homepage "https://github.com/Justintime50/1pass"
  url "https://github.com/Justintime50/1pass/archive/v0.1.1.tar.gz"
  sha256 "93c1bed478c5a1e7e4838a499683a3ca2106f7eac12656c07dce2335087075d1"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "src/1pass.sh" => "1pass"
  end
end
