# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alchemist < Formula
  desc "Update, backup, and administer your Homebrew or Chocolatey instances"
  homepage "https://github.com/Justintime50/alchemist"
  version "3.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.1.1/alchemist_3.1.1_darwin_amd64.tar.gz"
      sha256 "b54dfd4db49b10eb5a32aaacb97c84a67bc2022ed9f28bb76176e3c70dc8277d"

      def install
        bin.install "alchemist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.1.1/alchemist_3.1.1_darwin_arm64.tar.gz"
      sha256 "59c0977f4f7ff3ba33c58011ae26ace27efbc91d66ca03b4894324d1423343f6"

      def install
        bin.install "alchemist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.1.1/alchemist_3.1.1_linux_arm64.tar.gz"
      sha256 "12430cb622826d9f80048e7bab118dd425437808998e93e6c756b6d534f6b0d3"

      def install
        bin.install "alchemist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.1.1/alchemist_3.1.1_linux_amd64.tar.gz"
      sha256 "b497b625ffb4edad16e3a1b63e09640d749327f5909b5bbad3eba5400e0c52b5"

      def install
        bin.install "alchemist"
      end
    end
  end
end
