# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alchemist < Formula
  desc "Update, backup, and administer your Homebrew or Chocolatey instances"
  homepage "https://github.com/Justintime50/alchemist"
  version "3.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.2.0/alchemist_3.2.0_darwin_amd64.tar.gz"
      sha256 "ac29fbf4a267da80bd3074d77ceff15b3cd224c91b54d3a057ecb437ac6790ab"

      def install
        bin.install "alchemist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.2.0/alchemist_3.2.0_darwin_arm64.tar.gz"
      sha256 "17e1583c8b16afcdde310ee3c8038fe5242f28b6c8eebd9024ee1e574991c062"

      def install
        bin.install "alchemist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.2.0/alchemist_3.2.0_linux_arm64.tar.gz"
      sha256 "93898ce3cc093cfa5cf096d597d026904b9e93b20119f313d1012a82a53dd1ab"

      def install
        bin.install "alchemist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Justintime50/alchemist/releases/download/v3.2.0/alchemist_3.2.0_linux_amd64.tar.gz"
      sha256 "a1a0821c35b21e6bc6a78de938a048d6203fe7ae546e2d6302cc1094e1cb641b"

      def install
        bin.install "alchemist"
      end
    end
  end
end
