# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alchemist < Formula
  desc "Update, backup, and administer your Homebrew or Chocolatey instances"
  homepage "https://github.com/Justintime50/alchemist"
  version "4.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Justintime50/alchemist/releases/download/v4.0.0/alchemist_4.0.0_darwin_amd64.tar.gz"
      sha256 "a60307744a64aa68c4fa5c8984b67564b5574191012e1e478648dd4f88a8d6a2"

      def install
        bin.install "alchemist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Justintime50/alchemist/releases/download/v4.0.0/alchemist_4.0.0_darwin_arm64.tar.gz"
      sha256 "eff888240f658fdc8619ae92504ed5f1af7d7b519d20ff13e646f5bf735f9320"

      def install
        bin.install "alchemist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Justintime50/alchemist/releases/download/v4.0.0/alchemist_4.0.0_linux_amd64.tar.gz"
      sha256 "bca136c922531bfd980369bdcebd79d03bd971ce85f9e536cb0b8f0f2778c1e3"
      def install
        bin.install "alchemist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Justintime50/alchemist/releases/download/v4.0.0/alchemist_4.0.0_linux_arm64.tar.gz"
      sha256 "3243101ab0fe78df569b16e739e7ee1082b66dc7bad0707f8b57b6bc1907b2eb"
      def install
        bin.install "alchemist"
      end
    end
  end
end
