# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class BrewBackup < Formula
  desc "Backup your entire homebrew instance with a single command restore you"
  homepage "https://github.com/Justintime50/brew-backup"
  url "https://github.com/Justintime50/brew-backup/archive/v1.1.2.tar.gz"
  sha256 "81f78357910fa9ff52f8d974335786c8e223e65b0e8b08e57bddd043d4369bc2"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "src/brew-backup.sh" => "brew-backup"
  end
end
