# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class BrewUpdate < Formula
  desc "Automate the entire homebrew update process with just one command"
  homepage "https://github.com/Justintime50/brew-update"
  url "https://github.com/Justintime50/brew-update/archive/v1.2.1.tar.gz"
  sha256 "7d8cd0f8facd3527a85d0146f7e50e31764e086d6d2aae5812129e698711833f"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "src/brew-update.sh" => "brew-update"
  end
end
