# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class BurnNotice < Formula
  desc "Returning a machine to it, got let go, or got burned? delete your data with one"
  homepage "https://github.com/Justintime50/burn-notice"
  url "https://github.com/Justintime50/burn-notice/archive/v1.2.0.tar.gz"
  sha256 "e4f94e9b3f58338ceb3b05097b40c4a9a5207139a974dc26e94dad50800aced6"
  license "MIT"

  def install
    bin.install "src/burn-notice.sh" => "burn-notice"
  end
end
