# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clienv < Formula
  desc "Source your environment variables from env when running cli commands"
  homepage "https://github.com/Justintime50/clienv"
  url "https://github.com/Justintime50/clienv/archive/v0.1.0.tar.gz"
  sha256 "0287e6886a7d298021a8673743a620a7b6225444954e5a7d48a17e5c6ac93355"
  license "MIT"

  def install
    bin.install "src/clienv.sh" => "clienv"
  end
end
