# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clienv < Formula
  desc "Source your environment variables from env when running cli commands"
  homepage "https://github.com/Justintime50/clienv"
  url "https://github.com/Justintime50/clienv/archive/v0.2.0.tar.gz"
  sha256 "dc9426e748205af86c69886598e7e29d83463bd82d1ac566728f9f77ac6a5991"
  license "MIT"

  def install
    bin.install "src/clienv.sh" => "clienv"
  end
end
