# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clienv < Formula
  desc "Source your environment variables from env when running cli commands"
  homepage "https://github.com/Justintime50/clienv"
  url "https://github.com/Justintime50/clienv/archive/v0.2.1.tar.gz"
  sha256 "40e376aa0b82c222e4b605adf730c220017ef66fa611ea37de91b7d22a05a1bc"
  license "MIT"

  def install
    bin.install "src/clienv.sh" => "clienv"
  end
end
