# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deckschrubber < Formula
  desc "Deckschrubber inspects images of a Docker Registry and removes those older than a given age"
  homepage "https://github.com/Justintime50/deckschrubber"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Justintime50/deckschrubber/releases/download/v0.8.0/deckschrubber_0.8.0_darwin_amd64.tar.gz"
      sha256 "de63e3c3bf865aad1146193e13481b853d14ca9086b5dc1043a2ed42a73f8445"

      def install
        bin.install "deckschrubber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Justintime50/deckschrubber/releases/download/v0.8.0/deckschrubber_0.8.0_darwin_arm64.tar.gz"
      sha256 "780b0e3126007bd3e531e84cbc36b42bf6a77c04500f74af62ad264f99fb4d8b"

      def install
        bin.install "deckschrubber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Justintime50/deckschrubber/releases/download/v0.8.0/deckschrubber_0.8.0_linux_amd64.tar.gz"
        sha256 "4c5c6a0bd4c905cf2e06283ed27e281234dfbe829f552987f7b3fe50be152ff4"

        def install
          bin.install "deckschrubber"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Justintime50/deckschrubber/releases/download/v0.8.0/deckschrubber_0.8.0_linux_arm64.tar.gz"
        sha256 "ba29cfae7768fa4ab14509836fa63ae598fcd55100cc7d7530c248a09d832a05"

        def install
          bin.install "deckschrubber"
        end
      end
    end
  end
end
