# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EasypostCli < Formula
  desc "Easypost api on the cli"
  homepage "https://github.com/Justintime50/easypost-cli"
  url "https://github.com/Justintime50/easypost-cli/archive/v1.6.0.tar.gz"
  sha256 "608493b74bce874db74e3b2244a39462a9ba7b4f46515acd41b1e53722d30c4e"
  license "MIT"

  def install
    bin.install "dist/unix_ep.sh" => "ep"
  end
end
