# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EasypostCli < Formula
  desc "Easypost api on the cli"
  homepage "https://github.com/Justintime50/easypost-cli"
  url "https://github.com/Justintime50/easypost-cli/archive/v1.3.0.tar.gz"
  sha256 "5d84d6c2816cfcd6babc3da97412220984c91f12414dc30bfb3f03ebda150dc9"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "dist/unix_ep.sh" => "ep"
  end
end
