# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class EasypostCli < Formula
  desc "The EasyPost API on the CLI."
  homepage "https://github.com/Justintime50/easypost-cli"
  url "https://github.com/Justintime50/easypost-cli/archive/v1.2.0.tar.gz"
  sha256 "c45a58321b68e8177341f3edce1041e0d58c9d7c7efbb3f9c835f9c61cb14580"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "dist/unix_ep.sh" => "ep"
  end
end
