# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Freedom < Formula
  desc "Give your computer the freedom to do more"
  homepage "https://github.com/Justintime50/freedom"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Justintime50/freedom/releases/download/v0.3.1/freedom_0.3.1_darwin_amd64.tar.gz"
    sha256 "b6fd6960c2eac3e2ec2c605bbb585aa725eb6511e7793172ce0452e5762af629"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Justintime50/freedom/releases/download/v0.3.1/freedom_0.3.1_linux_amd64.tar.gz"
    sha256 "c2abc837fa4269bdea636cc7745172f912dabd0fe8d527f4283e9215c7594670"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/Justintime50/freedom/releases/download/v0.3.1/freedom_0.3.1_linux_arm64.tar.gz"
    sha256 "55816987edb83ce2f3c6b4d477f295d586bef247892ea884a15f09e8547b4933"
  end

  def install
    bin.install "freedom"
  end
end
