# This file was generated by GoReleaser. DO NOT EDIT.
class Freedom < Formula
  desc "Give your computer the freedom to do more"
  homepage "https://github.com/Justintime50/freedom"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Justintime50/freedom/releases/download/v0.3.0/freedom_0.3.0_darwin_amd64.tar.gz"
    sha256 "993f95bed3e4be9a1d734f475c0dfcdd84f1ecc9f7c8295367c57ead02148669"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/Justintime50/freedom/releases/download/v0.3.0/freedom_0.3.0_linux_amd64.tar.gz"
    sha256 "6d7714761b98886d33f84a7735d3eb94aab964d416ab118a7d473d3930ae6cb6"
  end

  def install
    bin.install "freedom"
  end
end
