# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GithubArchive < Formula
  include Language::Python::Virtualenv

  desc "Powerful tool to concurrently clone, pull, or fork user and org repos and gist"
  homepage "https://github.com/Justintime50/github-archive"
  url "https://github.com/Justintime50/github-archive/archive/refs/tags/v7.0.4.tar.gz"
  sha256 "38e8344d385a92fdc9f597fc07367f85c008150d036d0cba3e07bf13a196ff3c"
  license "MIT"

  depends_on "maturin" => :build
  depends_on "openssl@3"
  depends_on "python@3.14"
  depends_on "rust" => :build

  def install
    venv = virtualenv_create(libexec, "python3.14")
    venv.pip_install resources.reject { |r| r.name == "cryptography" }
    resource("cryptography").stage do
      system venv.root/"bin/pip", "install", "--no-build-isolation", "-v", "."
    end
    venv.pip_install_and_link buildpath
  end

  test do
    assert_match "github-archive #{version}", shell_output("#{bin}/github-archive --version")
  end
end
