# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Muffinscript < Formula
  desc "Delectable little programming language"
  homepage "https://github.com/Justintime50/muffinscript"
  url "https://github.com/Justintime50/muffinscript/releases/download/v0.1.0/v0.1.0.tar.gz"
  sha256 "fcff78d3ea4bd75df1863ef644bf3b16ec73af12bfc783f96a993dd56d141b97"
  license "MIT"

  def install
    bin.install "dist/muffin/muffin" => "muffin"
  end

  test do
    assert_match "Muffin", shell_output("#{bin}/muffin --version")
  end
end
