# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Muffinscript < Formula
  desc "Delectable little programming language"
  homepage "https://github.com/Justintime50/muffinscript"
  url "https://github.com/Justintime50/muffinscript/releases/download/v0.2.0/muffinscript.tar.gz"
  sha256 "aa47dfe98bbdb98d35f1e6a8938d1d828ac6fe937275ed9d68f1e99a0250fede"
  license "MIT"

  def install
    libexec.install "muffin"
    bin.install_symlink libexec/"muffin/muffin" => "muffin"
  end

  test do
    assert_match "Muffin", shell_output("#{bin}/muffin --version")
  end
end
