# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Muffinscript < Formula
  desc "Delectable little programming language"
  homepage "https://github.com/Justintime50/muffinscript"
  url "https://github.com/Justintime50/muffinscript/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "ebe3bc0834836c92cbd0b3c3edc25b76e0d0a501a2fab892f62966a8826b0314"
  license "MIT"

  def install
    (prefix/"muffin").install Dir["dist/*"]
    bin.install_symlink prefix/"muffin/muffin" => "muffin"
  end

  test do
    assert_match "Muffin", shell_output("#{bin}/muffin --version")
  end
end
