# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Onepass < Formula
  desc "1password cli wrapper for easy credential retrieval"
  homepage "https://github.com/Justintime50/onepass"
  url "https://github.com/Justintime50/onepass/archive/v0.1.1.tar.gz"
  sha256 "ac7b8db6c9375ac42c05f6c8c4e30e4fb73b770f0fb619d490cd5e050ece2282"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "src/onepass.sh" => "onepass"
  end
end
