# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class PipTree < Formula
  include Language::Python::Virtualenv

  desc "Get the dependency tree of your python virtual environment via pip"
  homepage "https://github.com/Justintime50/pip-tree"
  url "https://github.com/Justintime50/pip-tree/archive/refs/tags/v5.0.0.tar.gz"
  sha256 "a722d6f4581156c597b17594a3ef7f79b89ca4e9ef147f65020c74eb261dd207"
  license "MIT"

  depends_on "python@3.14"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "pip-tree #{version}", shell_output("#{bin}/pip-tree --version")
  end
end
