# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class PipTree < Formula
  include Language::Python::Virtualenv

  desc "Get the dependency tree of your python virtual environment via pip"
  homepage "https://github.com/Justintime50/pip-tree"
  url "https://github.com/Justintime50/pip-tree/archive/refs/tags/v4.0.0.tar.gz"
  sha256 "ebc5e8dd2c9541695443a88c5b74f0f36c4d6fd1ef8d1d40823c600e8c2dded8"
  license "MIT"

  depends_on "python@3.13"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "pip-tree #{version}", shell_output("#{bin}/pip-tree --version")
  end
end
