# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Portgrid < Formula
  desc "Agentic harness for claude or copilot to port code from one project to another"
  homepage "https://github.com/Justintime50/portgrid"
  url "https://github.com/Justintime50/portgrid/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "1c4ab45ed079f8d5e2afe85c92d5e0576cb31c1f038870f8196d34c0dc089d56"
  license "MIT"

  def install
    bin.install "src/portgrid.sh" => "portgrid"
  end
end
