# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Portgrid < Formula
  desc "Agentic harness for claude or copilot to port code from one project to another"
  homepage "https://github.com/Justintime50/portgrid"
  url "https://github.com/Justintime50/portgrid/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "f37a6217c18580e4d02e6be05cc65801b41b2657b6216466a09b9f801727bf12"
  license "MIT"

  def install
    bin.install "src/portgrid.sh" => "portgrid"
  end
end
