# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Portgrid < Formula
  desc "Agentic harness for claude or copilot to port code from one project to another"
  homepage "https://github.com/Justintime50/portgrid"
  url "https://github.com/Justintime50/portgrid/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "dde3f301ccbde340ec28d4778aca489b57f5ab941119196fe4a89f94d7a3a364"
  license "MIT"

  def install
    bin.install "src/portgrid.sh" => "portgrid"
  end
end
