# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SecureBrowserKiosk < Formula
  desc "Restart Chrome in incognito mode by prompting the user if"
  homepage "https://github.com/Justintime50/secure-browser-kiosk"
  url "https://github.com/Justintime50/secure-browser-kiosk/archive/v1.1.1.tar.gz"
  sha256 "536b20a4f08cb903126f2afd6ba3503664d271ac16492bfbf536014e2b1d592d"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "src/secure-browser-kiosk.sh" => "secure-browser-kiosk"
  end

  
end
