# frozen_string_literal: true
# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SecureBrowserKiosk < Formula
  desc "Restart Chrome in incognito mode by prompting the user if"
  homepage "https://github.com/Justintime50/secure-browser-kiosk"
  url "https://github.com/Justintime50/secure-browser-kiosk/archive/v1.1.1.tar.gz"
  sha256 "e91af9181b35d2dc176d7ce66ec2b0219f71dfeb6ced771cad26ae55b3584230"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "src/secure-browser-kiosk.sh" => "secure-browser-kiosk"
  end
end
