# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Srvinfra < Formula
  desc "Srvinfra is a tool to deploy and update services and websites on a server"
  homepage "https://github.com/Justintime50/srvinfra"
  url "https://github.com/Justintime50/srvinfra/archive/v0.2.0.tar.gz"
  sha256 "c747d99cfe6513a761de2fc03061efda7657df3e7fc8feb58b2596693cd18c05"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "src/srvinfra.sh" => "srvinfra"
  end
end
