# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Srvinfra < Formula
  desc "Srvinfra is a tool to deploy and update services and websites on a server"
  homepage "https://github.com/Justintime50/srvinfra"
  url "https://github.com/Justintime50/srvinfra/archive/v0.3.2.tar.gz"
  sha256 "562fab8b1b2ff2103c3dc7d9238032c2bd85b8c03de70ae4cbf570fd3990642c"
  license "MIT"

  def install
    bin.install "src/srvinfra.sh" => "srvinfra"
  end
end
