# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Srvinfra < Formula
  desc "Is a tool to deploy, update, and maintain services and websites on a se"
  homepage "https://github.com/Justintime50/srvinfra"
  url "https://github.com/Justintime50/srvinfra/archive/refs/tags/v1.2.1.tar.gz"
  sha256 "28b737d30077ac1b1e3c06ce91ea932363dbc57649cd9f9c883e1829be06d90c"
  license "MIT"

  def install
    bin.install "src/srvinfra.sh" => "srvinfra"
  end
end
