# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Srvinfra < Formula
  desc "Srvinfra is a tool to deploy, update, and maintain services and websites o"
  homepage "https://github.com/Justintime50/srvinfra"
  url "https://github.com/Justintime50/srvinfra/archive/v0.6.2.tar.gz"
  sha256 "a9e70d8bec3e7977bea2be6736d4eaf97e18c20ae0882a52192dbd3f0404e183"
  license "MIT"

  def install
    bin.install "src/srvinfra.sh" => "srvinfra"
  end
end
