# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class VcrpyBincon < Formula
  include Language::Python::Virtualenv

  desc "Convert binary python vcr cassette responses to human-readable strings"
  homepage "https://github.com/Justintime50/vcrpy-bincon"
  url "https://github.com/Justintime50/vcrpy-bincon/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "69cd95a98a30b8a669e85759504fc8a1033928efef2fedaff828e4e3e3e1bb32"
  license "MIT"

  depends_on "python@3.13"

  resource "ruamel-yaml" do
    url "https://files.pythonhosted.org/packages/39/87/6da0df742a4684263261c253f00edd5829e6aca970fff69e75028cccc547/ruamel.yaml-0.18.14.tar.gz"
    sha256 "7227b76aaec364df15936730efbf7d72b30c0b79b1d578bbb8e3dcb2d81f52b7"
  end

  resource "ruamel-yaml-clib" do
    url "https://files.pythonhosted.org/packages/20/84/80203abff8ea4993a87d823a5f632e4d92831ef75d404c9fc78d0176d2b5/ruamel.yaml.clib-0.2.12.tar.gz"
    sha256 "6c8fbb13ec503f99a91901ab46e0b07ae7941cd527393187039aec586fdfd36f"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "vcrpy-bincon #{version}", shell_output("#{bin}/vcrpy-bincon --version")
  end
end
