# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class VcrpyBincon < Formula
  include Language::Python::Virtualenv

  desc "Convert binary python vcr cassette responses to human-readable strings"
  homepage "https://github.com/Justintime50/vcrpy-bincon"
  url "https://github.com/Justintime50/vcrpy-bincon/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "97845ead8d10f40c150d9d71eef2996aca320e256d849403e541148b925b654c"
  license "MIT"

  depends_on "python@3.14"

  resource "ruamel-yaml" do
    url "https://files.pythonhosted.org/packages/9f/c7/ee630b29e04a672ecfc9b63227c87fd7a37eb67c1bf30fe95376437f897c/ruamel.yaml-0.18.16.tar.gz"
    sha256 "a6e587512f3c998b2225d68aa1f35111c29fad14aed561a26e73fab729ec5e5a"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "vcrpy-bincon #{version}", shell_output("#{bin}/vcrpy-bincon --version")
  end
end
